apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nebula-poc
  name: pillars-of-creation
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nebula-poc
  template:
    metadata:
      labels:
        name: nebula-poc
    spec:
      containers:
      - image: alexbob2/nebula-poc:39
        name: nebula-poc
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nebula-poc-service
spec:
  selector:
    name: nebula-poc
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nebula-poc
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nebula`)
      kind: Rule
      services:
        - name: nebula-poc-service
          port: 80